package.json, packages/astro/README.md, packages/astro/package.json, packages/astro/src/generators/application/files/astro.config.mjs__tmpl__, packages/astro/src/generators/application/files/snowpack.config.mjs__tmpl__, packages/astro/src/generators/application/generator.spec.ts, packages/astro/src/generators/application/schema.json, packages/astro/src/generators/init/generator.spec.ts, packages/astro/src/generators/init/generator.ts, packages/astro/src/generators/init/schema.json, packages/astro/src/generators/init/versions.ts, packages/astro/src/generators/library/schema.json, packages/astro/src/project-graph/plugin.ts, yarn.lock
Adds support for Astro 0.21.0 version.
Fixes #
=> feat(astro): add support for astro 0.21.0

package.json, packages/astro/README.md, packages/astro/package.json, packages/astro/src/executors/dev/executor.spec.ts, packages/astro/src/executors/dev/executor.ts, packages/astro/src/generators/application/files/src/pages/index.astro__tmpl__, packages/astro/src/generators/application/generator.spec.ts, packages/astro/src/generators/application/generator.ts, packages/astro/src/generators/application/schema.d.ts, packages/astro/src/generators/application/schema.json, packages/astro/src/generators/application/utilities/index.ts, packages/astro/src/generators/application/utilities/normalize-options.ts, packages/astro/src/generators/application/utilities/setup-e2e-tests.ts, packages/astro/src/generators/init/generator.spec.ts, packages/astro/src/generators/init/generator.ts, packages/astro/src/generators/init/schema.d.ts, packages/astro/src/generators/init/schema.json, packages/astro/src/generators/library/generator.ts, yarn.lock
Adds support for generating an e2e project with Cypress for Astro applications.
Fixes #5
=> feat(astro): add support for generating cypress e2e tests for applications

packages/astro/src/generators/init/generator.spec.ts, packages/astro/src/generators/init/generator.ts, packages/astro/src/generators/init/utilities/add-project-graph-plugin.ts, packages/astro/src/generators/init/utilities/add-vscode-recommended-extensions.ts, packages/astro/src/generators/init/utilities/index.ts, packages/astro/src/generators/init/utilities/update-gitignore.ts
=> feat(astro): add recommended vscode extensions for astro when creating projects if needed

packages/astro/src/project-graph/plugin.ts
Reverts the workaround done in https://github.com/nxtensions/nxtensions/pull/36. The issue is now fixed on Nx side.
Fixes #
=> fix(astro): remove workaround for project graph as it's fixed on nx side

packages/astro/README.md
=> docs(astro): update readme with an example on how to generate a component

packages/astro/src/generators/component/schema.json
=> fix(astro): fix component generator schema

package.json, packages/astro/package.json, packages/astro/src/generators/init/versions.ts, yarn.lock
=> feat(astro): support latest version (1.0.0-beta.56)

packages/astro/src/project-graph/plugin.ts
=> fix(astro): handle new projects correctly in project graph plugin

package.json, packages/astro/migrations.json, packages/astro/package.json, packages/astro/src/generators/init/versions.ts, yarn.lock
=> feat(astro): update astro to latest (1.3.0)

e2e/astro-e2e/tests/astro.spec.ts, e2e/e2e-utils/src/git.ts, e2e/e2e-utils/src/index.ts
=> test(astro): fix project graph plugin e2e tests

package.json, packages/astro/package.json, packages/astro/src/executors/build/executor.spec.ts, packages/astro/src/executors/build/executor.ts, packages/astro/src/executors/check/executor.spec.ts, packages/astro/src/executors/dev/executor.spec.ts, packages/astro/src/executors/preview/executor.spec.ts, packages/astro/src/generators/application/__snapshots__/generator.spec.ts.snap, packages/astro/src/generators/application/generator.ts, packages/astro/src/generators/application/utilities/add-project.ts, packages/astro/src/generators/application/utilities/setup-e2e-tests.ts, packages/astro/src/generators/init/generator.spec.ts, packages/astro/src/generators/init/generator.ts, packages/astro/src/generators/library/generator.ts, packages/astro/src/generators/utilities/cypress.ts, yarn.lock
=> feat(astro): add support for nx 15

package.json, packages/astro/package.json, packages/astro/src/generators/application/files/project/src/components/Card.astro__tmpl__, packages/astro/src/generators/application/files/project/src/layouts/Layout.astro__tmpl__, packages/astro/src/generators/application/files/project/src/pages/index.astro__tmpl__, yarn.lock
=> feat(astro): update astro dependencies

.husky/pre-push
=> chore(repo): check format on pre push

package.json, yarn.lock
=> chore(repo): bump deps

.github/workflows/main.yml, package.json, packages/astro/README.md, packages/astro/generators.json, packages/astro/src/generators/preset/generator.spec.ts, packages/astro/src/generators/preset/generator.ts, packages/astro/src/generators/preset/schema.d.ts, packages/astro/src/generators/preset/schema.json, yarn.lock
=> feat(astro): add a preset generator

packages/astro/src/generators/library/files/package.json__tmpl__
=> feat(astro): generate astro as a peer dependency for publishable libraries

e2e/astro/tests/astro.spec.ts, package.json, packages/astro/README.md, packages/astro/executors.json, packages/astro/src/executors/sync/executor.spec.ts, packages/astro/src/executors/sync/executor.ts, packages/astro/src/executors/sync/schema.d.ts, packages/astro/src/executors/sync/schema.json, packages/astro/src/generators/application/__snapshots__/generator.spec.ts.snap, packages/astro/src/generators/application/utilities/add-project.ts, packages/astro/src/utilities/package-json.ts, packages/astro/src/utilities/versions.ts, yarn.lock
=> feat(astro): add sync executor

packages/astro/src/generators/init/versions.ts
=> feat(astro): generate new workspaces with astro ^1.8.0

packages/astro/src/generators/init/generator.ts
=> fix(astro): ensure the plugin is not initialized multiple times

packages/astro/src/executors/build/schema.json
=> fix(astro): fix build executor support for astro supported config file types

e2e/astro/tests/astro.spec.ts, package.json, packages/astro/package.json, packages/astro/src/generators/application/files/project/src/env.d.ts__tmpl__, packages/astro/src/generators/application/files/project/tsconfig.json__tmpl__, packages/astro/src/generators/application/generator.spec.ts, packages/astro/src/generators/init/generator.spec.ts, packages/astro/src/generators/init/utilities/update-gitignore.ts, packages/astro/src/generators/init/versions.ts, packages/astro/src/generators/library/files/src/env.d.ts__tmpl__, packages/astro/src/generators/library/files/tsconfig.json__tmpl__, packages/astro/src/migrations/update-1-4-0/add-check-target.spec.ts, packages/astro/src/utilities/package-json.ts, yarn.lock
=> feat(astro): add support for astro v2

e2e/astro/tests/astro.spec.ts
=> test(astro): improve astro content collections e2e tests

packages/astro/README.md
=> docs(readme): fix a type

package.json, packages/astro/package.json, packages/astro/src/migrations/update-2-1-0/remove-experimental-static-build.ts, yarn.lock
=> feat(astro): update dependencies

packages/astro/src/generators/application/utilities/add-integrations-packages.ts, packages/astro/src/generators/component/utilities/add-style-dependencies.ts, packages/astro/src/generators/init/generator.ts, packages/astro/src/utilities/package-json.spec.ts, packages/astro/src/utilities/package-json.ts
=> fix(astro): do not overwrite existing dependencies in generators

e2e/astro/tests/astro.spec.ts, packages/astro/src/generators/application/generator.ts, packages/astro/src/generators/application/utilities/configure-tailwind-integration.ts, packages/astro/src/generators/application/utilities/index.ts, packages/astro/src/migrations/update-2-1-0/remove-experimental-static-build.ts
Generates the right configuration for the `@astrojs/tailwind` integration. The recently released version 4.0.0 of that integration contains some breaking changes https://github.com/withastro/astro/blob/main/packages/integrations/tailwind/CHANGELOG.md#400. Now, we need to provide the tailwind config path to it because it's no longer resolved from the project root.
Fixes #446 
Fixes #447
=> fix(astro): generate correct tailwind integration config

packages/astro/src/generators/application/files/project/tsconfig.json__tmpl__, packages/astro/src/generators/application/generator.spec.ts, packages/astro/src/generators/application/utilities/add-files.ts, packages/astro/src/generators/library/files/tsconfig.json__tmpl__, packages/astro/src/generators/library/generator.spec.ts, packages/astro/src/generators/library/utilities/add-files.ts, packages/astro/src/generators/utilities/versions.ts
=> fix(astro): sync generated tsconfig with astro defaults

packages/astro/src/generators/application/generator.ts, packages/astro/src/generators/application/utilities/configure-tailwind-integration.ts
=> fix(astro): import tsquery lazily in application generator

package.json, packages/astro/src/generators/init/versions.ts, yarn.lock
=> feat(astro): restore usage of astro's latest version

packages/astro/src/generators/application/files/project/tsconfig.json__tmpl__
=> fix(astro): set explicit include setting to generated app tsconfig

packages/astro/generators.json, packages/astro/src/generators/library/generator.spec.ts, packages/astro/src/generators/library/generator.ts, packages/astro/src/generators/library/schema.d.ts, packages/astro/src/generators/library/schema.json, packages/astro/src/generators/library/utilities/add-project.ts, packages/astro/src/generators/library/utilities/normalize-options.ts
=> feat(astro): allow generating libraries with project name and directory as provided

e2e/astro/tests/astro.spec.ts, packages/astro/package.json, packages/astro/src/generators/application/__snapshots__/generator.spec.ts.snap, packages/astro/src/generators/application/generator.spec.ts, packages/astro/src/generators/application/utilities/setup-e2e-tests.ts
=> feat(astro): allow cypress generator to infer targets

e2e/astro/tests/astro.spec.ts, e2e/utils/src/e2e-test-runners.ts, e2e/utils/src/index.ts, package.json, packages/astro/package.json, packages/astro/src/generators/application/__snapshots__/generator.spec.ts.snap, packages/astro/src/generators/application/generator.spec.ts, packages/astro/src/generators/application/schema.d.ts, packages/astro/src/generators/application/schema.json, packages/astro/src/generators/application/utilities/add-integrations-packages.ts, packages/astro/src/generators/application/utilities/normalize-options.ts, packages/astro/src/generators/application/utilities/setup-e2e-tests.ts, packages/astro/src/generators/preset/generator.ts, pnpm-lock.yaml
=> feat(astro): add support for generating apps with playwright e2e tests

packages/astro/README.md
=> docs(astro): update readme

packages/astro/src/generators/init/schema.json
Address the issue reported in the comment: https://github.com/nxtensions/nxtensions/issues/592#issuecomment-2014302864.
Fixes #
=> fix(astro): allow passing additional properties to the nx init generator

packages/astro/src/executors/build/executor.spec.ts, packages/astro/src/executors/build/executor.ts, packages/astro/src/executors/check/executor.spec.ts, packages/astro/src/executors/check/executor.ts, packages/astro/src/executors/dev/executor.spec.ts, packages/astro/src/executors/dev/executor.ts, packages/astro/src/executors/preview/executor.spec.ts, packages/astro/src/executors/preview/executor.ts, packages/astro/src/executors/sync/executor.spec.ts, packages/astro/src/executors/sync/executor.ts, packages/astro/src/generators/utilities/testing.ts, packages/astro/src/generators/utilities/versions.ts, packages/astro/src/migrations/update-17-0-0/add-astro-check-dependencies.ts, packages/astro/src/migrations/update-18-0-0/remove-patch-nx-cli-script.ts, packages/astro/src/utilities/astro.ts, packages/astro/src/utilities/package-json.ts
=> fix(astro): resolve and execute astro cli binary

e2e/astro/project.json, nx.json, packages/astro/project.json, packages/astro/src/generators/application/generator.spec.ts, packages/astro/src/generators/utilities/testing.ts
=> chore(repo): infer jest tasks

tools/scripts/release-project.ts
=> chore(repo): fix release script

tools/scripts/release-project.ts
=> chore(repo): ensure release process exit
